//热门大赛
export const FETCH_HOT_LIST = 'FETCH_HOT_LIST';
export const RECEIVE_HOT_LIST = 'RECEIVE_HOT_LIST';


//大赛介绍
export const FETCH_HOT_INTRO= 'FETCH_HOT_INTRO';
export const RECEIVE_HOT_INTRO = 'RECEIVE_HOT_INTRO';
export const RESET_HOT_INTRO = 'RESET_HOT_INTRO';

//大赛每日信息
export const FETCH_HOT_DAY_LIST = 'FETCH_HOT_DAY_LIST';
export const RECEIVE_HOT_DAY_LIST = 'RECEIVE_HOT_DAY_LIST';
export const RESET_HOT_DAY_LIST = 'RESET_HOT_DAY_LIST';

export const FETCH_HOT_DAY_DETAIL = 'FETCH_HOT_DAY_DETAIL';



//获取奖金结构表
export const FETCH_MATCH_SETTING= 'FETCH_MATCH_SETTING';
export const RECEIVE_MATCH_SETTING = 'RECEIVE_MATCH_SETTING';
export const RESET_MATCH_SETTING = 'RESET_MATCH_SETTING';

//获取日赛结果
export const FETCH_DAILY_MATCH_RESULT= 'FETCH_DAILY_MATCH_RESULT';
export const RECEIVE_DAILY_MATCH_RESULT = 'RECEIVE_DAILY_MATCH_RESULT';
export const RESET_DAILY_MATCH_RESULT = 'RESET_DAILY_MATCH_RESULT';


//日赛列表
export const FETCH_DAILY_LIST = 'FETCH_DAILY_LIST';
export const RECEIVE_DAILY_LIST = 'RECEIVE_DAILY_LIST';
export const CHANGE_DAILY_CITY_SHOW_STATUS = 'CHANGE_DAILY_CITY_SHOW_STATUS';



export const FETCH_DAILY_INFO_LIST = 'FETCH_DAILY_INFO_LIST';
export const RECEIVE_DAILY_INFO_LIST = 'RECEIVE_DAILY_INFO_LIST';
export const RESET_DAILY_INFO_LIST = 'RESET_DAILY_INFO_LIST';

//大赛系列
export const FETCH_SCHEDULE_LIST = 'FETCH_SCHEDULE_LIST';
export const RECEIVE_SCHEDULE_LIST = 'RECEIVE_SCHEDULE_LIST';
export const RECEIVE_AREA_LIST = 'RECEIVE_AREA_LIST'
export const RECEIVE_TOUR_LIST = 'RECEIVE_TOUR_LIST'
export const CHANGE_SCHEDULE_SELECTED = 'CHANGE_SCHEDULE_CITY_SELECTED_STATUS';
export const CHANGE_SELECTE_CONTENT_SHOW = 'CHANGE_SELECTE_CONTENT_SHOW';

// 进入大赛
export const FETCH_SCHEDULE_DETAIL= 'FETCH_SCHEDULE_DETAIL';
export const RECEIVE_SCHEDULE_DETAIL = 'RECEIVE_SCHEDULE_DETAIL';
export const RESET_SCHEDULE_DETAIL = 'RESET_SCHEDULE_DETAIL';

//城市列表
export const FETCH_CITY_LIST = 'FETCH_CITY_LIST'
export const RECEIVE_CITY_LIST = 'RECEIVE_CITY_LIST'

//获取验证码
export const FETCH_SMSCODE = 'FETCH_SMSCODE'
export const RECEIVE_SMSCODE = 'RECEIVE_SMSCODE'

//校验验证码
export const FETCH_TOKEN = 'FETCH_TOKEN'
export const RECEIVE_TOKEN = 'RECEIVE_TOKEN'

//倒数60秒计时器
export const START_TIMER_ELSE = 'START_TIMER_ELSE'
export const STOP_TIMER_ELSE = 'STOP_TIMER_ELSE'
export const SET_ELSE_TIME = 'SET_ELSE_TIME'

//注册设置密码
export const FETCH_REGPWD = 'FETCH_REGPWD'
export const RECEIVE_REGPWD = 'RECEIVE_REGPWD'

//用户登陆 登出
export const FETCH_USERLOGIN = 'FETCH_USERLOGIN'
export const RECEIVE_USERLOGIN  = 'RECEIVE_USERLOGIN'

export const FETCH_USERLOGOUT = 'FETCH_USERLOGOUT'
export const RECEIVE_USERLOGOUT = 'RECEIVE_USERLOGOUT'

export const FETCH_USERLOGIN_WITH_TOKEN = 'FETCH_USERLOGIN_WITH_TOKEN'
export const RECEIVE_USERLOGIN_WITH_TOKEN = 'RECEIVE_USERLOGIN_WITH_TOKEN'

//用户信息
export const FETCH_ACCOUNTINFO = 'FETCH_ACCOUNTINFO'
export const RECEIVE_ACCOUNTINFO  = 'RECEIVE_ACCOUNTINFO'
export const SET_ACCOUNTINFO  = 'SET_ACCOUNTINFO'
export const UPDATE_ACCOUNTINFO = 'UPDATE_ACCOUNTINFO'


//订票
export const FETCH_ADD_ORDER = 'FETCH_ADD_ORDER'
export const RECEIVE_ADD_ORDER = 'RECEIVE_ADD_ORDER'

export const FETCH_PAY_WX_INFO= 'FETCH_PAY_WX_INFO'
export const RECEIVE_PAY_WX_INFO = 'RECEIVE_PAY_WX_INFO'

export const FETCH_PAY_ORDER= 'FETCH_PAY_ORDER'
export const RECEIVE_PAY_ORDER = 'RECEIVE_PAY_ORDER'

//门票
export const FETCH_TICKETS = 'FETCH_TICKETS'
export const RECEIVE_TICKETS  = 'RECEIVE_TICKETS'

//订单
export const FETCH_ORDERS = 'FETCH_ORDERS'
export const RECEIVE_ORDERS  = 'RECEIVE_ORDERS'
